#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset
python manage.py makemigrations
python manage.py migrate
#python /app/manage.py createsuperuser --noinput --username admin --email <email>
exec python manage.py runserver 0.0.0.0:8000
