version: "3"

volumes:
  enterpriseviz_local_postgres_data: {}
  enterpriseviz_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: enterpriseviz_local_django
    container_name: enterpriseviz_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend/:/app:z
    env_file:
      - ./.envs/.local/backend/.django
      - ./.envs/.local/backend/.postgres
    command: /start
    ports:
      - "80:8000"

  postgres:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    image: enterpriseviz_local_postgres
    container_name: enterpriseviz_local_postgres
    volumes:
      - enterpriseviz_local_postgres_data:/var/lib/postgresql/data
      - enterpriseviz_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/backend/.postgres

  redis:
    image: redis:6
    container_name: enterpriseviz_local_redis

  celeryworker:
    <<: *django
    image: enterpriseviz_local_celeryworker
    container_name: enterpriseviz_local_celeryworker
    depends_on:
      - redis
      - postgres
    command: /start-celeryworker
    ports: []

  celerybeat:
    <<: *django
    image: enterpriseviz_local_celerybeat
    container_name: enterpriseviz_local_celerybeat
    depends_on:
      - redis
      - postgres
    command: /start-celerybeat
    ports: []
