"""
Django settings for enterpriseviz project.

Generated by 'django-admin startproject' using Django 3.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

import environ
from csp.constants import NONE, SELF, UNSAFE_INLINE, UNSAFE_EVAL, NONCE

BASE_DIR = Path(__file__).resolve(strict=True).parent.parent.parent

APPS_DIR = BASE_DIR / "config"
env = environ.Env()

# Read the .env file one level above BASE_DIR whenever it exists.
#
# BASE_DIR is the directory IIS is pointed at as the site's physical path, so a
# .env inside it would sit under the web root. Nothing serves it today, but the
# file holds the database password, the ArcGIS client secret and the key that
# decrypts every stored portal credential — so it lives in the parent, where the
# web server has no path to it at all:
#
#     D:\apps\enterpriseviz\.env          <- here
#     D:\apps\enterpriseviz\backend\      <- IIS physical path (BASE_DIR)
#
# Defaulting this on matters on Windows, where a Scheduled Task action has no
# environment-variable field and a second console session does not inherit the
# first one's. A missing .env is a no-op, and real environment variables still
# win over the file, so containers and CI that inject configuration directly are
# unaffected.
READ_DOT_ENV_FILE = env.bool("DJANGO_READ_DOT_ENV_FILE", default=True)
if READ_DOT_ENV_FILE:
    _env_file = BASE_DIR.parent / ".env"
    if _env_file.is_file():
        # OS environment variables take precedence over variables from .env
        env.read_env(str(_env_file))

# GENERAL
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/dev/ref/settings/#debug
DEBUG = env.bool("DJANGO_DEBUG", False)

# Internationalization
# https://docs.djangoproject.com/en/dev/ref/settings/#language-code
LANGUAGE_CODE = "en-us"

# Local time zone. Choices are
# http://en.wikipedia.org/wiki/List_of_tz_zones_by_name
# though not all of them may be available with every OS.
# In Windows, this must be set to your system time zone.
TIME_ZONE = "America/Los_Angeles"

# https://docs.djangoproject.com/en/dev/ref/settings/#use-i18n
USE_I18N = False

# https://docs.djangoproject.com/en/dev/ref/settings/#site-id
SITE_ID = 1

# https://docs.djangoproject.com/en/dev/ref/settings/#use-tz
USE_TZ = False

DATETIME_FORMAT = 'M j, Y h:i A'
DATE_FORMAT = 'M j, Y'
DATE_INPUT_FORMATS = ['YYYY-mm-dd']

TIME_FORMAT = "H:i"
USE_L10N = False

# URLS
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/dev/ref/settings/#root-urlconf
ROOT_URLCONF = "config.urls"
# https://docs.djangoproject.com/en/dev/ref/settings/#wsgi-application
WSGI_APPLICATION = "config.wsgi.application"
URL_PREFIX = None

# APPS
# ------------------------------------------------------------------------------
DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

]
THIRD_PARTY_APPS = [
    'django_htmx',
    'django_celery_beat',
    'social_django',
    'django_tables2',
    'django_filters',
    'csp',
]

LOCAL_APPS = [
    'app'
    # Your stuff: custom apps go here
]
# https://docs.djangoproject.com/en/dev/ref/settings/#installed-apps
INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    'csp.middleware.CSPMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # Default-closed authentication; views opt out with @login_not_required.
    "app.auth_middleware.AppLoginRequiredMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'django_htmx.middleware.HtmxMiddleware',
    'config.customArcGIS.MySocialAuthExceptionMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
    "app.middleware.RequestContextLogMiddleware",
]

AUTHENTICATION_BACKENDS = (
    'config.customArcGIS.PortalOAuth2',

    'django.contrib.auth.backends.ModelBackend',
)

# PASSWORDS
# ------------------------------------------------------------------------------
# Applies to local Django accounts, including the superuser created from
# DJANGO_SUPERUSER_PASSWORD. Accounts that sign in through the portal are
# authenticated by ArcGIS and never have a usable password here.
# https://docs.djangoproject.com/en/dev/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
     "OPTIONS": {"min_length": 12}},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# How many reverse proxies sit in front of this deployment and append to
# X-Forwarded-For. See app.middleware.client_ip.
#
# 0 means the header is ignored and REMOTE_ADDR is used, which is correct for
# the IIS layout — HttpPlatformHandler proxies from loopback and adds no
# X-Forwarded-For, so any value present came from the client. Raise it only to
# the number of proxies you actually run: each one you claim is an entry an
# attacker gets to choose.
TRUSTED_PROXY_COUNT = env.int("TRUSTED_PROXY_COUNT", default=0)

# Failed sign-in throttling. See app.throttling; both counters must stay under
# their limit for an attempt to proceed.
LOGIN_RATELIMIT_ATTEMPTS = env.int("LOGIN_RATELIMIT_ATTEMPTS", default=10)
LOGIN_RATELIMIT_WINDOW = env.int("LOGIN_RATELIMIT_WINDOW", default=900)
WEBHOOK_RATELIMIT_ATTEMPTS = env.int("WEBHOOK_RATELIMIT_ATTEMPTS", default=20)
WEBHOOK_RATELIMIT_WINDOW = env.int("WEBHOOK_RATELIMIT_WINDOW", default=300)

# STATIC
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/dev/ref/settings/#static-root
STATIC_ROOT = str(BASE_DIR / "staticfiles")
# https://docs.djangoproject.com/en/dev/ref/settings/#static-url
STATIC_URL = f"/static/"
# https://docs.djangoproject.com/en/dev/ref/contrib/staticfiles/#std:setting-STATICFILES_DIRS
STATICFILES_DIRS = ()
# https://docs.djangoproject.com/en/dev/ref/contrib/staticfiles/#staticfiles-finders
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

APPEND_SLASH = True

LOGIN_URL = "/enterpriseviz/login/"
LOGIN_REDIRECT_URL = "/enterpriseviz/"
LOGOUT_REDIRECT_URL = "/enterpriseviz/"

SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',  # 0
    'social_core.pipeline.social_auth.social_uid',  # 1
    'social_core.pipeline.social_auth.auth_allowed',  # 2
    'config.customArcGIS.user_role',
    'social_core.pipeline.social_auth.social_user',  # 3
    'social_core.pipeline.user.get_username',  # 4
    'social_core.pipeline.user.create_user',
    # 'social_core.pipeline.social_auth.associate_by_email',  # 5
    'social_core.pipeline.social_auth.associate_user',  # 6
    'social_core.pipeline.social_auth.load_extra_data',  # 7
    'social_core.pipeline.user.user_details',  # 8
)

USE_SERVICE_USAGE_REPORT = env.bool("USE_SERVICE_USAGE_REPORT", default=True)

# MEDIA
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/dev/ref/settings/#media-root
MEDIA_ROOT = str(BASE_DIR / "media")
# https://docs.djangoproject.com/en/dev/ref/settings/#media-url
MEDIA_URL = f"/media/"

# TEMPLATES
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/dev/ref/settings/#templates
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
            'libraries': {
                'filter_tags': 'app.templatetags.filter',
            }
        },
    },
]

# SECURITY
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/dev/ref/settings/#session-cookie-httponly
SESSION_COOKIE_HTTPONLY = True
# https://docs.djangoproject.com/en/dev/ref/settings/#csrf-cookie-httponly
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = True
# https://docs.djangoproject.com/en/dev/ref/settings/#x-frame-options
X_FRAME_OPTIONS = "DENY"

# ADMIN
# ------------------------------------------------------------------------------
# Django Admin URL.
ADMIN_URL = "admin/"
WEBHOOK_URL = "webhook/"

# https://docs.djangoproject.com/en/dev/ref/settings/#admins
ADMINS = []
# https://docs.djangoproject.com/en/dev/ref/settings/#managers
MANAGERS = ADMINS

# LOGGING
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/dev/ref/settings/#logging
# See https://docs.djangoproject.com/en/dev/topics/logging for
# more details on how to customize your logging configuration.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    'filters': {
        'combined_context_filter': {
            '()': 'app.log_handlers.CombinedContextFilter',
        }
    },
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {asctime} {name}: {message}",
            "style": "{",
        },
        "database": {
            "format": "{message}",
            "style": "{",
        }
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "simple",
            'filters': ['combined_context_filter'],  # Also filter console output for context
        },
        "database": {
            "level": "DEBUG",
            "class": "app.log_handlers.DatabaseLogHandler",
            'filters': ['combined_context_filter'],  # Apply the context filter
            "formatter": "database",
        },
    },
    "loggers": {
        "root": {
            "level": "WARNING",
            "handlers": ["console"],
        },
        "django": {
            "handlers": ["console", "database"],
            "level": "WARNING",
            "propagate": True,
        },
        "django.server": {
            "handlers": ["database"],
            "level": "WARNING",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": True,
        },
        "enterpriseviz.jobs": {  # Queueing, claiming and running background jobs
            "handlers": ["console", "database"],
            "level": "INFO",
            "propagate": False,
        },
        "enterpriseviz.worker": {  # The run_worker loop and its scheduler
            "handlers": ["console", "database"],
            "level": "INFO",
            "propagate": False,
        },
        "enterpriseviz": {
            "handlers": ["console", "database"],
            "level": "INFO",
            "propagate": False,
        },
        "enterpriseviz.utils": {
            "handlers": ["console", "database"],
            "level": "INFO",
            "propagate": False,
        },
        "enterpriseviz.tasks": {
            "handlers": ["console", "database"],
            "level": "INFO",
            "propagate": False,
        },

    },

}

# BACKGROUND JOBS
# ------------------------------------------------------------------------------
DJANGO_CELERY_BEAT_TZ_AWARE = bool(USE_TZ)

# How many jobs one worker runs at once.
JOB_CONCURRENCY = env.int("JOB_CONCURRENCY", default=2)
# How many batches a single job may fan out to.
JOB_BATCH_CONCURRENCY = env.int("JOB_BATCH_CONCURRENCY", default=8)
# Seconds between polls of the queue. The progress bar polls every 3 seconds,
# so anything below that is latency nobody can see.
JOB_POLL_INTERVAL = env.float("JOB_POLL_INTERVAL", default=3.0)
# A RUNNING job whose worker has not written a heartbeat in this long is
# treated as orphaned by a crashed worker and returned to the queue.
JOB_HEARTBEAT_TIMEOUT = env.int("JOB_HEARTBEAT_TIMEOUT", default=300)
# How many times a worker may claim the same job before it is failed instead of
# requeued.
JOB_MAX_ATTEMPTS = env.int("JOB_MAX_ATTEMPTS", default=3)

# CSP_INCLUDE_NONCE_IN = ['style-src', 'script-src']


CSP_ARCGIS = "https://js.arcgis.com"
CSP_DATATABLES = "https://cdn.datatables.net/"

CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {
        "default-src": [SELF],

        "script-src": [
            SELF,
            CSP_ARCGIS,
            CSP_DATATABLES,
            "https://cdnjs.cloudflare.com/ajax/libs/cytoscape/",
            "https://cdnjs.cloudflare.com/ajax/libs/dagre/",
            "https://cdnjs.cloudflare.com/ajax/libs/htmx/",
            "https://cdnjs.cloudflare.com/ajax/libs/pdfmake/",
            "https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/",
            # Exact versions, matching the script tags in base_site.html. None
            # of these end in a slash, so CSP requires an exact path match -
            # bumping a version here without bumping it there (or the reverse)
            # blocks the script, which is what the @^1 encoding bug did.
            "https://cdn.jsdelivr.net/npm/chart.js@4.5.1",
            "https://cdn.jsdelivr.net/npm/chartjs-adapter-moment@1.0.1",
            "https://cdn.jsdelivr.net/npm/chartjs-plugin-autocolors@0.3.1",
            "https://cdn.jsdelivr.net/npm/cytoscape-dagre@2.5.0/",
            "https://cdn.jsdelivr.net/npm/d3@3.0.0/",
            "https://unpkg.com/htmx-ext-loading-states@2.0.0/",
        ],

        "style-src": [
            SELF,
            CSP_ARCGIS,
            CSP_DATATABLES,
            "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/",
            "https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/",
            UNSAFE_INLINE
        ],

        "img-src": [
            SELF,
            "https://raw.githubusercontent.com",
            "data:",
        ],

        "font-src": [
            SELF,
            CSP_ARCGIS,
            "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/",
        ],

        "connect-src": [
            SELF,
            CSP_ARCGIS,
        ],

        "worker-src": [
            SELF,
        ],

        "frame-src": [NONE],
        "object-src": [NONE],
        "base-uri": [SELF],
        "form-action": [SELF],
        "frame-ancestors": [NONE],
        "manifest-src": [SELF],
        "media-src": [SELF],

    }
}

# DATABASE CONNECTIONS
# ------------------------------------------------------------------------------
#: A second connection to the same database, used only to rotate OAuth refresh
#: tokens. See configure_databases() and app.utils._ensure_oauth_access_token.
OAUTH_DB_ALIAS = "oauth"

#: Seconds the OAuth connection waits for the portal row lock before giving up
#: and refreshing without it. Bounded so a request can never hang here.
OAUTH_LOCK_TIMEOUT = env.int("OAUTH_LOCK_TIMEOUT", default=5)


def configure_databases(databases):
    """
    Turn ATOMIC_REQUESTS on, and add the connection OAuth refreshes run on.

    ATOMIC_REQUESTS wraps each request in one transaction, which is what this
    application wants everywhere except one place. Refreshing an OAuth token is
    not a database write that can be taken back: the portal invalidates the old
    refresh token the moment it issues the new one. Store the new one inside the
    request transaction and any later rollback loses it while the old one is
    already dead — the portal is then locked out until an administrator consents
    again.

    A second connection to the same database fixes that. It has its own
    transaction, so the rotated token is committed the instant the refresh
    succeeds, whatever the request goes on to do. It also means SELECT ... FOR
    UPDATE on the portal row is held for the length of the refresh rather than
    the length of the request, so a slow page cannot block the worker from
    refreshing the same portal.

    Mirrored for tests so the runner reuses the one test database instead of
    building a second.
    """
    import copy

    default = databases["default"]
    default["ATOMIC_REQUESTS"] = True

    oauth = copy.deepcopy(default)
    # This connection exists to commit on its own; wrapping it in the request
    # transaction would defeat the entire point of having it.
    oauth["ATOMIC_REQUESTS"] = False
    # Held open no longer than a refresh needs. Persisting it would mean a
    # second idle connection per web worker for something used rarely.
    oauth["CONN_MAX_AGE"] = 0
    oauth["TEST"] = {"MIRROR": "default"}
    databases[OAUTH_DB_ALIAS] = oauth

    return databases


CREDENTIAL_ENCRYPTION_KEY = env('CREDENTIAL_ENCRYPTION_KEY', default=None)

# How long a temporary portal credential stays readable, in seconds.
CREDENTIAL_TOKEN_TTL = env.int("CREDENTIAL_TOKEN_TTL", default=900)


# ARCGIS TLS
# ------------------------------------------------------------------------------
def _tls_verify_setting(raw):
    """
    Interpret a TLS verification env var as a bool or a CA bundle path.

    Accepts "true"/"false" (and the usual synonyms) or a filesystem path, which
    is what both requests' verify= and arcgis' verify_cert= take.
    """
    value = (raw or "").strip().strip("'\" ")
    if not value:
        return True
    if value.lower() in ("true", "yes", "on", "1"):
        return True
    if value.lower() in ("false", "no", "off", "0"):
        return False
    return value


# Whether to validate the portal's TLS certificate on every connection to it.
ARCGIS_VERIFY_TLS = _tls_verify_setting(env("ARCGIS_VERIFY_TLS", default=""))
