"""
Django settings for enterpriseviz project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os, logging

# from dotenv import load_dotenv
# load_dotenv()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = str(os.getenv('SECRET_KEY'))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# if DEBUG:
#     # will output to your console
#     logging.basicConfig(
#         level = logging.DEBUG,
#         format = '%(asctime)s %(levelname)s %(message)s',
#     )

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'social_django',
    'app',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',
    'enterpriseviz.customArcGIS.MySocialAuthExceptionMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'enterpriseviz.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
            'libraries': {
                'filter_tags': 'app.templatetags.filter',
            }
        },
    },
]

AUTHENTICATION_BACKENDS = (
    'enterpriseviz.customArcGIS.PortalOAuth2',

    'django.contrib.auth.backends.ModelBackend',
)

WSGI_APPLICATION = 'enterpriseviz.wsgi.application'

APPEND_SLASH = True

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

# POSTGRES
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'db',
#         'USER': 'admin@gisviz',
#         'PASSWORD': 'gisviz',
#         'HOST': 'gisviz.postgres.database.azure.com',
#         # 'PORT': ''
#     }
# }
# SQLITE
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = ""
# SOCIAL_AUTH_ARCGIS_KEY = os.getenv('SOCIAL_AUTH_ARCGIS_KEY')
# SOCIAL_AUTH_ARCGIS_SECRET = os.getenv('SOCIAL_AUTH_ARCGIS_SECRET')
# SOCIAL_AUTH_ARCGIS_URL = os.getenv('SOCIAL_AUTH_ARCGIS_URL')
# ARCGIS_USER_ROLE = os.getenv('ARCGIS_USER_ROLE')
# USE_SERVICE_USAGE_REPORT = os.getenv('USE_SERVICE_USAGE_REPORT')

SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',  # 0
    'social_core.pipeline.social_auth.social_uid',  # 1
    'social_core.pipeline.social_auth.auth_allowed',  # 2
    'enterpriseviz.customArcGIS.user_role',
    'social_core.pipeline.social_auth.social_user',  # 3
    'social_core.pipeline.user.get_username',  # 4
    'social_core.pipeline.user.create_user',
    # 'social_core.pipeline.social_auth.associate_by_email',  # 5
    'social_core.pipeline.social_auth.associate_user',  # 6
    'social_core.pipeline.social_auth.load_extra_data',  # 7
    'social_core.pipeline.user.user_details',  # 8
)

# SESSION_COOKIE_SECURE = False
# SOCIAL_AUTH_ARCGIS_WHITELISTED_EMAILS = ["*"]
# SOCIAL_AUTH_ARCGIS_WHITELISTED_DOMAINS = ["*"]
# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_L10N = False

# USE_TZ = False

DATETIME_FORMAT = 'D, F jS, Y, g:i:s A'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

STATIC_ROOT = os.path.join(BASE_DIR, "app/static")

SECRET_KEY = '!ez28)k(^a5^s@m4is^==81604#^oj@5quu79-vvj(j7m*f1xi'
SOCIAL_AUTH_ARCGIS_KEY = ''
SOCIAL_AUTH_ARCGIS_SECRET = ''
SOCIAL_AUTH_ARCGIS_URL = ''
ARCGIS_USER_ROLE = 'org_admin'
USE_SERVICE_USAGE_REPORT = True

# SECURE_SSL_REDIRECT = True
# SECURE_HSTS_SECONDS = 15768000
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_BROWSER_XSS_FILTER = True

CSP_DEFAULT_SRC = ["'none'"]
CSP_SCRIPT_SRC = [
    "https://code.jquery.com",
    "https://cdn.jsdelivr.net",
    "https://cdnjs.cloudflare.com",
    "https://cdn.datatables.net",
    "https://d3js.org",
    "'sha256-JFEX3umdcAQBdD/brbt/Hxz2Gm6lUErPc8d1PM47+Do='",  # layer chart
    "'self'",
]
CSP_STYLE_SRC = [
    "https://cdn.jsdelivr.net",
    "https://cdn.datatables.net",
    "https://cdnjs.cloudflare.com",
    "'self'",
    "'sha256-DxxaJ/iVp+IBMDD8r4H7YeQwjR5AMwIcdsYe0+t4oNg='",  # layer style
    "'sha256-z7zcnw/4WalZqx+PrNaRnoeLz/G9WXuFqV1WCJ129sg='",  # layer style for chart
    "'sha256-e09hlj/IWDMJdhnf08u3EkBQ/Y3jM0R3lZycSyd0vG0='",  # add portal style
    "'sha256-HP6/UfBxn2b1cG+U0cEJiZtEMlVDaTs70ium0CpD+3k='",  # map style
]
CSP_IMG_SRC = [
    "https://cdnjs.cloudflare.com",
    "'self'"
]
CSP_FONT_SRC = [
    "https://cdnjs.cloudflare.com",
    "https://cdn.datatables.net",
    "'self'"
]
CSP_BASE_URI = ["'none'"]
CSP_FRAME_ANCESTORS = ["'none'"]
