# Generated by Django 5.2.1 on 2025-06-02 23:08

import django.contrib.postgres.fields
import django.db.models.deletion
import django_cryptography.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    # This depended on django_celery_beat 0019_alter_periodictasks_options,
    # which is not a real requirement. The only thing needed from that app is
    # the PeriodicTask model that Portal.task points at, and it is created in
    # its 0001_initial; 0019 is an AlterModelOptions changing verbose names on
    # a different model and touches no schema.
    #
    # makemigrations pins to whatever was the latest migration of a referenced
    # app at the moment the file was written. That made this migration claim to
    # need a django-celery-beat newer than the one any existing database was
    # built with, and Django then refuses to run at all:
    #
    #   InconsistentMigrationHistory: Migration app.0001_initial is applied
    #   before its dependency django_celery_beat.0019_alter_periodictasks_options
    #
    # Pointing at 0001_initial states the actual requirement and lets a
    # database created against an older django-celery-beat migrate forward.
    dependencies = [
        ("django_celery_beat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="App",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_id", models.CharField(max_length=50, verbose_name="App Id")),
                ("app_title", models.TextField(null=True, verbose_name="Title")),
                ("app_url", models.TextField(null=True, verbose_name="URL")),
                (
                    "app_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Web Mapping Application", "Web Mapping Application"),
                            ("Story Map", "Story Map"),
                            ("Experience Builder", "Experience Builder"),
                            ("Dashboard", "Dashboard"),
                            ("Web AppBuilder Apps", "Web AppBuilder Apps"),
                            ("Form", "Form"),
                        ],
                        null=True,
                        verbose_name="Type",
                    ),
                ),
                (
                    "app_created",
                    models.DateTimeField(blank=True, verbose_name="Created"),
                ),
                (
                    "app_modified",
                    models.DateTimeField(blank=True, verbose_name="Modified"),
                ),
                (
                    "app_access",
                    models.CharField(
                        blank=True, max_length=1000, verbose_name="Access"
                    ),
                ),
                (
                    "app_extent",
                    models.CharField(
                        blank=True, max_length=1000, verbose_name="Extent"
                    ),
                ),
                (
                    "app_description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "app_snippet",
                    models.TextField(blank=True, null=True, verbose_name="Snippet"),
                ),
                (
                    "app_views",
                    models.IntegerField(blank=True, null=True, verbose_name="Views"),
                ),
                (
                    "app_dependent",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "app_usage",
                    models.JSONField(blank=True, null=True, verbose_name="Usage"),
                ),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
                (
                    "app_last_viewed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Viewed"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "request_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Django request ID or ID passed from Celery task caller",
                        null=True,
                        verbose_name="Request ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "request_username",
                    models.CharField(
                        blank=True,
                        help_text="Username",
                        max_length=150,
                        null=True,
                        verbose_name="Username",
                    ),
                ),
                (
                    "client_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Client IP"
                    ),
                ),
                (
                    "request_path",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "request_method",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "request_duration",
                    models.FloatField(
                        blank=True,
                        help_text="Time from request/task start to log in ms",
                        null=True,
                    ),
                ),
                ("logger_name", models.CharField(db_index=True, max_length=255)),
                ("message", models.TextField()),
                ("pathname", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "funcName",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Function Name",
                    ),
                ),
                (
                    "lineno",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Line Number"
                    ),
                ),
                ("traceback", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Log Entry",
                "verbose_name_plural": "Log Entries",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "admin_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("email_host", models.CharField(blank=True, max_length=255, null=True)),
                ("email_port", models.PositiveIntegerField(default=25, null=True)),
                (
                    "email_encryption",
                    models.CharField(
                        choices=[
                            ("plain_text", "Plain Text"),
                            ("starttls", "StartTLS"),
                            ("ssl", "SSL"),
                        ],
                        default="plain_text",
                        max_length=255,
                    ),
                ),
                (
                    "email_username",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "email_password",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "from_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("reply_to", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "logging_level",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("DEBUG", "Debug"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="warning",
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Portal",
            fields=[
                (
                    "alias",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Alias",
                    ),
                ),
                ("url", models.TextField(verbose_name="URL")),
                ("store_password", models.BooleanField(default=False)),
                (
                    "portal_type",
                    models.CharField(
                        choices=[
                            ("agol", "ArcGIS Online"),
                            ("portal", "Enterprise Portal"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("username", models.TextField(blank=True)),
                (
                    "password",
                    django_cryptography.fields.encrypt(models.TextField(blank=True)),
                ),
                (
                    "token",
                    django_cryptography.fields.encrypt(models.TextField(blank=True)),
                ),
                ("token_expiration", models.DateTimeField(blank=True, null=True)),
                ("webmap_updated", models.DateTimeField(blank=True, null=True)),
                ("service_updated", models.DateTimeField(blank=True, null=True)),
                ("webapp_updated", models.DateTimeField(blank=True, null=True)),
                ("user_updated", models.DateTimeField(blank=True, null=True)),
                (
                    "org_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Org Id"
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_celery_beat.periodictask",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Layer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("layer_server", models.TextField(null=True, verbose_name="Server")),
                ("layer_version", models.TextField(null=True, verbose_name="Version")),
                (
                    "layer_database",
                    models.TextField(null=True, verbose_name="Database"),
                ),
                ("layer_name", models.TextField(null=True, verbose_name="Name")),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
                (
                    "layer_last_viewed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Viewed"
                    ),
                ),
                (
                    "portal_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.portal"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="App_Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rel_type",
                    models.CharField(
                        choices=[
                            ("widget", "widget"),
                            ("search", "search"),
                            ("filter", "filter"),
                            ("other", "other"),
                        ],
                        null=True,
                    ),
                ),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
                (
                    "app_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.app"
                    ),
                ),
                (
                    "portal_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.portal"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="app",
            name="portal_instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.portal"
            ),
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_name",
                    models.TextField(blank=True, null=True, verbose_name="Name"),
                ),
                (
                    "service_url",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(max_length=1024),
                        blank=True,
                        help_text="List of URLs for this service (e.g., MapServer, FeatureServer).",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "service_layers",
                    models.JSONField(default=dict, verbose_name="Layers"),
                ),
                (
                    "service_mxd_server",
                    models.TextField(
                        blank=True, null=True, verbose_name="Publish Server"
                    ),
                ),
                (
                    "service_mxd",
                    models.TextField(blank=True, null=True, verbose_name="Publish Map"),
                ),
                ("service_type", models.TextField(verbose_name="Type")),
                (
                    "service_access",
                    models.TextField(blank=True, null=True, verbose_name="Access"),
                ),
                (
                    "service_description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "service_snippet",
                    models.TextField(blank=True, null=True, verbose_name="Snippet"),
                ),
                (
                    "service_usage",
                    models.JSONField(blank=True, null=True, verbose_name="Usage"),
                ),
                (
                    "service_usage_trend",
                    models.IntegerField(blank=True, null=True, verbose_name="Trend"),
                ),
                ("portal_id", models.JSONField(default=dict, verbose_name="Portal Id")),
                (
                    "service_last_viewed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Viewed"
                    ),
                ),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
                (
                    "apps",
                    models.ManyToManyField(through="app.App_Service", to="app.app"),
                ),
                (
                    "portal_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.portal"
                    ),
                ),
                (
                    "service_view",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.service",
                        verbose_name="View",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Map_Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
                (
                    "portal_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.portal"
                    ),
                ),
                (
                    "service_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.service"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Layer_Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
                (
                    "layer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.layer"
                    ),
                ),
                (
                    "portal_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.portal"
                    ),
                ),
                (
                    "service_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.service"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="layer",
            name="services",
            field=models.ManyToManyField(through="app.Layer_Service", to="app.service"),
        ),
        migrations.AddField(
            model_name="app_service",
            name="service_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.service"
            ),
        ),
        migrations.AddField(
            model_name="app",
            name="services",
            field=models.ManyToManyField(through="app.App_Service", to="app.service"),
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_username",
                    models.CharField(max_length=50, verbose_name="Username"),
                ),
                (
                    "user_first_name",
                    models.CharField(max_length=50, verbose_name="First Name"),
                ),
                (
                    "user_last_name",
                    models.CharField(max_length=50, verbose_name="Last Name"),
                ),
                ("user_email", models.CharField(max_length=50, verbose_name="Email")),
                (
                    "user_created",
                    models.DateTimeField(blank=True, verbose_name="Created"),
                ),
                (
                    "user_last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Login"
                    ),
                ),
                ("user_role", models.CharField(max_length=50, verbose_name="Role")),
                ("user_level", models.CharField(max_length=50, verbose_name="Level")),
                ("user_disabled", models.BooleanField()),
                (
                    "user_provider",
                    models.CharField(max_length=10, verbose_name="Provider"),
                ),
                (
                    "user_pro_license",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("desktopAdvN", "Advanced"),
                            ("desktopBasicN", "Basic"),
                            ("desktopStdN", "Standard"),
                        ],
                        max_length=32,
                        null=True,
                        verbose_name="Pro License",
                    ),
                ),
                (
                    "user_pro_last",
                    models.DateField(blank=True, null=True, verbose_name="Pro Login"),
                ),
                (
                    "user_items",
                    models.IntegerField(blank=True, null=True, verbose_name="Items"),
                ),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
                (
                    "portal_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.portal"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="service",
            name="service_owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.user",
                verbose_name="Owner",
            ),
        ),
        migrations.AddField(
            model_name="app",
            name="app_owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.user",
                verbose_name="Owner",
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("light", "light"), ("dark", "dark")],
                        default="light",
                        max_length=10,
                    ),
                ),
                ("service_usage", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Webmap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "webmap_id",
                    models.CharField(max_length=50, verbose_name="Webmap ID"),
                ),
                ("webmap_title", models.TextField(null=True, verbose_name="Title")),
                ("webmap_url", models.TextField(null=True, verbose_name="URL")),
                (
                    "webmap_created",
                    models.DateTimeField(blank=True, verbose_name="Created"),
                ),
                (
                    "webmap_modified",
                    models.DateTimeField(blank=True, verbose_name="Modified"),
                ),
                (
                    "webmap_access",
                    models.CharField(blank=True, max_length=200, verbose_name="Access"),
                ),
                (
                    "webmap_extent",
                    models.CharField(blank=True, max_length=100, verbose_name="Extent"),
                ),
                (
                    "webmap_description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "webmap_snippet",
                    models.TextField(blank=True, null=True, verbose_name="Snippet"),
                ),
                (
                    "webmap_views",
                    models.IntegerField(blank=True, null=True, verbose_name="Views"),
                ),
                (
                    "webmap_layers",
                    models.JSONField(default=dict, verbose_name="Layers"),
                ),
                (
                    "webmap_services",
                    models.TextField(blank=True, null=True, verbose_name="Services"),
                ),
                (
                    "webmap_dependency",
                    models.JSONField(
                        blank=True, default=list, null=True, verbose_name="Dependency"
                    ),
                ),
                (
                    "webmap_usage",
                    models.JSONField(blank=True, null=True, verbose_name="Usage"),
                ),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
                (
                    "webmap_last_viewed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Viewed"
                    ),
                ),
                (
                    "portal_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.portal"
                    ),
                ),
                (
                    "webmap_owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.user",
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "ordering": ["webmap_title"],
            },
        ),
        migrations.AddField(
            model_name="service",
            name="maps",
            field=models.ManyToManyField(through="app.Map_Service", to="app.webmap"),
        ),
        migrations.AddField(
            model_name="map_service",
            name="webmap_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.webmap"
            ),
        ),
        migrations.CreateModel(
            name="Map_Layer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
                (
                    "layer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.layer"
                    ),
                ),
                (
                    "portal_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.portal"
                    ),
                ),
                (
                    "webmap_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.webmap"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="App_Map",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rel_type",
                    models.CharField(
                        choices=[
                            ("widget", "widget"),
                            ("search", "search"),
                            ("filter", "filter"),
                            ("map", "map"),
                            ("other", "other"),
                        ],
                        null=True,
                    ),
                ),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
                (
                    "app_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.app"
                    ),
                ),
                (
                    "portal_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.portal"
                    ),
                ),
                (
                    "webmap_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.webmap"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="app",
            name="maps",
            field=models.ManyToManyField(through="app.App_Map", to="app.webmap"),
        ),
    ]
