# Generated by Django 5.2.4 on 2025-07-22 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalToolSettings",
            fields=[
                (
                    "portal",
                    models.OneToOneField(
                        help_text="The Portal these tool settings apply to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="tool_settings",
                        serialize=False,
                        to="app.portal",
                    ),
                ),
                (
                    "tool_pro_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable ArcGIS Pro license removal tool.",
                    ),
                ),
                (
                    "tool_pro_duration",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (30, "30 days"),
                            (60, "60 days"),
                            (90, "90 days"),
                            (180, "180 days"),
                        ],
                        default=30,
                        help_text="Duration of inactivity before Pro license is considered for removal.",
                        null=True,
                    ),
                ),
                (
                    "tool_pro_warning",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (3, "3 days"),
                            (5, "5 days"),
                            (7, "7 days"),
                            (14, "14 days"),
                        ],
                        default=3,
                        help_text="Days before removal to send a warning notification.",
                        null=True,
                    ),
                ),
                (
                    "tool_public_unshare_enabled",
                    models.BooleanField(
                        default=False, help_text="Enable public item unsharing tool."
                    ),
                ),
                (
                    "tool_public_unshare_score",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(50, "50%"), (75, "75%"), (90, "90%"), (100, "100%")],
                        default=50,
                        help_text="Minimum metadata score required for items to remain public.",
                        null=True,
                    ),
                ),
                (
                    "tool_public_unshare_warning",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (3, "3 days"),
                            (5, "5 days"),
                            (7, "7 days"),
                            (14, "14 days"),
                        ],
                        default=3,
                        help_text="Days before unsharing to send a warning notification.",
                        null=True,
                    ),
                ),
                (
                    "tool_public_unshare_trigger",
                    models.CharField(
                        blank=True,
                        choices=[("webhook", "Webhook"), ("daily", "Daily Schedule")],
                        default="daily",
                        help_text="Choose how the unsharing process is triggered.",
                        max_length=10,
                        null=True,
                        verbose_name="Public Item Unsharing Trigger",
                    ),
                ),
                (
                    "tool_inactive_user_enabled",
                    models.BooleanField(
                        default=False, help_text="Enable inactive user management tool."
                    ),
                ),
                (
                    "tool_inactive_user_duration",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (30, "30 days"),
                            (60, "60 days"),
                            (90, "90 days"),
                            (180, "180 days"),
                            (365, "365 days"),
                        ],
                        default=30,
                        help_text="Duration of inactivity before user is considered for action.",
                        null=True,
                    ),
                ),
                (
                    "tool_inactive_user_warning",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (3, "3 days"),
                            (5, "5 days"),
                            (7, "7 days"),
                            (14, "14 days"),
                            (30, "30 days"),
                        ],
                        default=3,
                        help_text="Days before action to send a warning notification.",
                        null=True,
                    ),
                ),
                (
                    "tool_inactive_user_action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("notify", "Notify Only"),
                            ("disable", "Disable User"),
                            ("delete", "Delete User"),
                            ("transfer", "Transfer User Content"),
                        ],
                        default="disable",
                        help_text="Action to take for inactive users.",
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Portal Tool Settings",
                "verbose_name_plural": "Portal Tool Settings",
            },
        ),
    ]
