# Generated by Django 5.2.4 on 2025-08-01 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_portaltoolsettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portaltoolsettings",
            name="tool_public_unshare_warning",
        ),
        migrations.AddField(
            model_name="portaltoolsettings",
            name="tool_public_unshare_grace_period",
            field=models.PositiveIntegerField(
                default=24,
                help_text="Hours to wait before sending another notification email for public item unsharing (prevents spam).",
            ),
        ),
        migrations.CreateModel(
            name="WebhookNotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_id",
                    models.CharField(
                        help_text="ID of the item that triggered the notification.",
                        max_length=100,
                    ),
                ),
                (
                    "owner",
                    models.CharField(
                        help_text="Username of the item owner who received the notification.",
                        max_length=100,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("public_unshare_webhook", "Public Item Unshare Webhook")
                        ],
                        help_text="Type of notification sent.",
                        max_length=50,
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the notification was sent."
                    ),
                ),
                (
                    "item_title",
                    models.CharField(
                        blank=True,
                        help_text="Title of the item (for reference).",
                        max_length=200,
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of the item (for reference).",
                        max_length=100,
                    ),
                ),
                (
                    "portal",
                    models.ForeignKey(
                        help_text="The Portal this notification belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_notifications",
                        to="app.portal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Notification Log",
                "verbose_name_plural": "Webhook Notification Logs",
                "indexes": [
                    models.Index(
                        fields=["portal", "item_id", "sent_at"],
                        name="app_webhook_portal__47fbe1_idx",
                    ),
                    models.Index(
                        fields=["portal", "owner", "sent_at"],
                        name="app_webhook_portal__695275_idx",
                    ),
                    models.Index(
                        fields=["sent_at"], name="app_webhook_sent_at_bbe195_idx"
                    ),
                ],
            },
        ),
    ]
