# Generated by Django 5.2.4 on 2025-08-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_remove_portaltoolsettings_tool_public_unshare_warning_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portaltoolsettings",
            name="tool_public_unshare_grace_period",
            field=models.PositiveIntegerField(
                blank=True,
                default=24,
                help_text="Hours to wait before sending another notification email for public item unsharing (prevents spam).",
                null=True,
            ),
        ),
    ]
