# Generated by Django 5.2.4 on 2025-08-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_portaltoolsettings_tool_public_unshare_grace_period"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portaltoolsettings",
            name="tool_pro_enabled",
        ),
        migrations.AddField(
            model_name="portaltoolsettings",
            name="tool_pro_license_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable ArcGIS Pro license removal tool."
            ),
        ),
    ]
