# Generated by Django 5.2.4 on 2025-08-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_remove_portaltoolsettings_tool_pro_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portal",
            name="admin_emails",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated list of admin email addresses for tool notifications",
            ),
        ),
        migrations.AddField(
            model_name="portal",
            name="enable_admin_notifications",
            field=models.BooleanField(
                default=True,
                help_text="Enable/disable admin notifications for this portal",
            ),
        ),
        migrations.AlterField(
            model_name="portaltoolsettings",
            name="tool_inactive_user_action",
            field=models.CharField(
                choices=[
                    ("notify", "Notify Only"),
                    ("disable", "Disable User"),
                    ("delete", "Delete User"),
                    ("transfer", "Transfer User Content"),
                ],
                default="disable",
                help_text="Action to take for inactive users.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="portaltoolsettings",
            name="tool_inactive_user_duration",
            field=models.PositiveIntegerField(
                choices=[
                    (30, "30 days"),
                    (60, "60 days"),
                    (90, "90 days"),
                    (180, "180 days"),
                    (365, "365 days"),
                ],
                default=30,
                help_text="Duration of inactivity before user is considered for action.",
            ),
        ),
        migrations.AlterField(
            model_name="portaltoolsettings",
            name="tool_inactive_user_warning",
            field=models.PositiveIntegerField(
                choices=[
                    (3, "3 days"),
                    (5, "5 days"),
                    (7, "7 days"),
                    (14, "14 days"),
                    (30, "30 days"),
                ],
                default=3,
                help_text="Days before action to send a warning notification.",
            ),
        ),
        migrations.AlterField(
            model_name="portaltoolsettings",
            name="tool_pro_duration",
            field=models.PositiveIntegerField(
                choices=[
                    (30, "30 days"),
                    (60, "60 days"),
                    (90, "90 days"),
                    (180, "180 days"),
                ],
                default=30,
                help_text="Duration of inactivity before Pro license is considered for removal.",
            ),
        ),
        migrations.AlterField(
            model_name="portaltoolsettings",
            name="tool_pro_warning",
            field=models.PositiveIntegerField(
                choices=[(3, "3 days"), (5, "5 days"), (7, "7 days"), (14, "14 days")],
                default=3,
                help_text="Days before removal to send a warning notification.",
            ),
        ),
        migrations.AlterField(
            model_name="portaltoolsettings",
            name="tool_public_unshare_grace_period",
            field=models.PositiveIntegerField(
                default=24,
                help_text="Hours to wait before sending another notification email for public item unsharing (prevents spam).",
            ),
        ),
        migrations.AlterField(
            model_name="portaltoolsettings",
            name="tool_public_unshare_score",
            field=models.PositiveIntegerField(
                choices=[(50, "50%"), (75, "75%"), (90, "90%"), (100, "100%")],
                default=50,
                help_text="Minimum metadata score required for items to remain public.",
            ),
        ),
        migrations.AlterField(
            model_name="portaltoolsettings",
            name="tool_public_unshare_trigger",
            field=models.CharField(
                choices=[("webhook", "Webhook"), ("daily", "Daily Schedule")],
                default="daily",
                help_text="Choose how the unsharing process is triggered.",
                max_length=10,
                verbose_name="Public Item Unsharing Trigger",
            ),
        ),
    ]
