# Generated by Django 5.2.4 on 2025-09-02 22:15

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_portal_admin_emails_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="portaltoolsettings",
            old_name="tool_public_unshare_grace_period",
            new_name="tool_public_unshare_notify_limit",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="webhook_secret",
            field=django_cryptography.fields.encrypt(
                models.CharField(blank=True, max_length=255, null=True)
            ),
        ),
    ]
