# Generated by Django 5.2.8 on 2025-11-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "app",
            "0007_rename_tool_public_unshare_grace_period_portaltoolsettings_tool_public_unshare_notify_limit_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="layers",
            field=models.ManyToManyField(through="app.Layer_Service", to="app.layer"),
        ),
    ]
