# Generated by Django 5.2.8 on 2025-12-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_service_layers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app_map",
            name="rel_type",
            field=models.CharField(
                choices=[
                    ("widget", "widget"),
                    ("search", "search"),
                    ("filter", "filter"),
                    ("map", "Primary Map Reference"),
                    ("datasource", "Data Source Map"),
                    ("widget", "Widget Map"),
                    ("storymap", "StoryMap Embed"),
                    ("other", "Other"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="app_service",
            name="rel_type",
            field=models.CharField(
                choices=[
                    ("search", "Search Layer"),
                    ("filter", "Filter"),
                    ("widget", "Widget"),
                    ("datasource", "Data Source"),
                    ("dataset", "Dashboard Dataset"),
                    ("arcade", "Arcade Expression"),
                    ("survey", "Survey123 Form"),
                    ("embed", "StoryMap Embed"),
                    ("other", "Other"),
                ],
                null=True,
            ),
        ),
    ]
