# Generated by Django 5.2.8 on 2025-12-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_alter_app_map_rel_type_alter_app_service_rel_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="layer_service",
            name="service_layer_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="layer_service",
            name="service_layer_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="map_service",
            name="service_layer_id",
            field=models.IntegerField(
                blank=True,
                help_text="Specific layer ID from this service used in the webmap",
                null=True,
            ),
        ),
    ]
