# Generated by Django 5.2.8 on 2025-12-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_layer_service_service_layer_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="map_service",
            name="webmap_layer_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="layer_service",
            name="service_layer_id",
            field=models.IntegerField(
                blank=True,
                help_text="The layer ID within the service (e.g., 0, 1, 2 from /MapServer/0)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="layer_service",
            name="service_layer_name",
            field=models.CharField(
                blank=True,
                help_text="The display name of the layer in the service",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="layer_service",
            unique_together={("portal_instance", "layer_id", "service_id")},
        ),
        migrations.AlterUniqueTogether(
            name="map_service",
            unique_together={
                ("portal_instance", "webmap_id", "service_id", "service_layer_id")
            },
        ),
        migrations.AddIndex(
            model_name="layer_service",
            index=models.Index(
                fields=["service_id", "service_layer_id"], name="idx_service_layer"
            ),
        ),
        migrations.AddIndex(
            model_name="map_service",
            index=models.Index(
                fields=["webmap_id", "webmap_layer_id"],
                name="app_map_ser_webmap__edecc0_idx",
            ),
        ),
        migrations.AlterModelTable(
            name="layer_service",
            table="layer_service",
        ),
    ]
