# Generated by Django 5.2.8 on 2025-12-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_map_service_webmap_layer_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app_map",
            name="rel_type",
            field=models.CharField(
                choices=[
                    ("widget", "Widget"),
                    ("search", "Search"),
                    ("filter", "Filter"),
                    ("map", "Primary Map Reference"),
                    ("datasource", "Data Source Map"),
                    ("widget", "Widget Map"),
                    ("storymap", "StoryMap Embed"),
                    ("other", "Other"),
                ],
                null=True,
            ),
        ),
    ]
