# Generated by Django 5.2.8 on 2026-01-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_alter_app_map_rel_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="app_service",
            name="service_layer_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="service_created",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Created"),
        ),
        migrations.AddField(
            model_name="service",
            name="service_modified",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Modified"),
        ),
        migrations.AlterField(
            model_name="app_map",
            name="rel_type",
            field=models.CharField(
                choices=[
                    ("search", "Search"),
                    ("filter", "Filter"),
                    ("map", "Primary Map Reference"),
                    ("datasource", "Data Source Map"),
                    ("widget", "Widget Map"),
                    ("storymap", "StoryMap Embed"),
                    ("other", "Other"),
                ],
                null=True,
            ),
        ),
    ]
