# Generated by Django 5.2.8

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0013_app_service_service_layer_id_service_service_created_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReplacementJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "source_service_name",
                    models.TextField(help_text="Denormalized service name; survives Service deletion."),
                ),
                (
                    "replacement_config",
                    models.JSONField(
                        default=dict,
                        help_text="Raw UI input: {'mode': 'simple', 'target_service_id': n} or {'mode': 'advanced', 'layer_mappings': [...]}.",
                    ),
                ),
                (
                    "replacement_pairs",
                    models.JSONField(
                        default=list, help_text="Ordered [[old, new], ...] string pairs computed at dry-run."
                    ),
                ),
                ("selected_map_ids", models.JSONField(default=list)),
                ("selected_app_ids", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("dry_run", "Dry Run"),
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("completed_errors", "Completed with errors"),
                            ("failed", "Failed"),
                            ("reverting", "Reverting"),
                            ("reverted", "Reverted"),
                        ],
                        default="dry_run",
                        max_length=20,
                    ),
                ),
                (
                    "dry_run_summary",
                    models.JSONField(
                        default=dict, help_text="{'items': [...], 'warnings': [...], 'totals': {...}}"
                    ),
                ),
                ("celery_task_id", models.CharField(blank=True, max_length=100)),
                ("revert_task_id", models.CharField(blank=True, max_length=100)),
                ("error_message", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("reverted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "portal_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replacement_jobs",
                        to="app.portal",
                    ),
                ),
                (
                    "source_service",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replacement_jobs",
                        to="app.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Replacement Job",
                "verbose_name_plural": "Replacement Jobs",
                "ordering": ["-created"],
                "indexes": [
                    models.Index(fields=["portal_instance", "status"], name="app_replace_portal__51c2e8_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="ReplacementItemBackup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("item_id", models.CharField(max_length=50)),
                ("item_type", models.CharField(blank=True, max_length=100)),
                ("item_title", models.TextField(blank=True)),
                ("item_owner", models.CharField(blank=True, max_length=100)),
                ("url_property", models.TextField(blank=True, null=True)),
                ("data_text", models.TextField(blank=True, null=True)),
                (
                    "resources",
                    models.JSONField(
                        default=dict, help_text="{resource_name: pre-change text} for changing resources only."
                    ),
                ),
                (
                    "item_modified_at",
                    models.BigIntegerField(help_text="item.modified epoch ms at backup time.", null=True),
                ),
                (
                    "counts",
                    models.JSONField(
                        default=dict, help_text="{'url': n, 'data': n, 'resources': n} replacements applied."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("analyzed", "Analyzed"),
                            ("applied", "Applied"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                            ("stale", "Stale"),
                            ("reverted", "Reverted"),
                            ("revert_failed", "Revert Failed"),
                        ],
                        default="analyzed",
                        max_length=20,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_backups",
                        to="app.replacementjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Replacement Item Backup",
                "verbose_name_plural": "Replacement Item Backups",
                "unique_together": {("job", "item_id")},
            },
        ),
    ]
