# Generated by Django 5.2.8 on 2026-07-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0014_replacementjob_replacementitembackup"),
    ]

    operations = [
        migrations.AddField(
            model_name="replacementitembackup",
            name="applied_modified_at",
            field=models.BigIntegerField(
                help_text="item.modified epoch ms right after this job updated the item; lets revert detect (and flag) edits made after the replacement.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="replacementitembackup",
            name="status",
            field=models.CharField(
                choices=[
                    ("analyzed", "Analyzed"),
                    ("applied", "Applied"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                    ("reverted", "Reverted"),
                    ("revert_failed", "Revert Failed"),
                ],
                default="analyzed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="replacementjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("analyzing", "Analyzing"),
                    ("dry_run", "Dry Run"),
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("completed_errors", "Completed with errors"),
                    ("failed", "Failed"),
                    ("reverting", "Reverting"),
                    ("reverted", "Reverted"),
                ],
                default="dry_run",
                max_length=20,
            ),
        ),
    ]
