# Generated by Django 5.2.8 on 2026-07-09 23:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0015_replacementitembackup_applied_modified_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="replacementjob",
            name="status_updated",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="When status last changed; anchors abandoned-job cleanup.",
            ),
        ),
    ]
