# Generated by Django 5.2.8 on 2026-07-10 20:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0016_replacementjob_status_updated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="replacementjob",
            name="initiated_by",
        ),
        migrations.RemoveField(
            model_name="replacementjob",
            name="portal_instance",
        ),
        migrations.RemoveField(
            model_name="replacementjob",
            name="source_service",
        ),
        migrations.DeleteModel(
            name="ReplacementItemBackup",
        ),
        migrations.DeleteModel(
            name="ReplacementJob",
        ),
    ]
