# Generated by Django 5.2.8 on 2026-07-18 12:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0017_remove_replacementjob_initiated_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReplacementJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_service_name",
                    models.TextField(
                        help_text="Denormalized service name; survives Service deletion."
                    ),
                ),
                (
                    "replacement_config",
                    models.JSONField(
                        default=dict,
                        help_text="Raw UI input: {'mode': 'simple', 'target_service_id': n} or {'mode': 'advanced', 'layer_mappings': [...]}.",
                    ),
                ),
                (
                    "replacement_pairs",
                    models.JSONField(
                        default=list,
                        help_text="Ordered [[old, new], ...] string pairs computed at dry-run.",
                    ),
                ),
                ("selected_map_ids", models.JSONField(default=list)),
                ("selected_app_ids", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("analyzing", "Analyzing"),
                            ("dry_run", "Dry Run"),
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("completed_errors", "Completed with errors"),
                            ("failed", "Failed"),
                            ("reverting", "Reverting"),
                            ("reverted", "Reverted"),
                        ],
                        default="dry_run",
                        max_length=20,
                    ),
                ),
                (
                    "dry_run_summary",
                    models.JSONField(
                        default=dict,
                        help_text="{'items': [...], 'warnings': [...], 'totals': {...}}",
                    ),
                ),
                ("celery_task_id", models.CharField(blank=True, max_length=100)),
                ("revert_task_id", models.CharField(blank=True, max_length=100)),
                ("error_message", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "status_updated",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When status last changed; anchors abandoned-job cleanup.",
                    ),
                ),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("reverted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "portal_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replacement_jobs",
                        to="app.portal",
                    ),
                ),
                (
                    "source_service",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replacement_jobs",
                        to="app.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Replacement Job",
                "verbose_name_plural": "Replacement Jobs",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="ReplacementItemBackup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_id", models.CharField(max_length=50)),
                ("item_type", models.CharField(blank=True, max_length=100)),
                ("item_title", models.TextField(blank=True)),
                ("item_owner", models.CharField(blank=True, max_length=100)),
                ("url_property", models.TextField(blank=True, null=True)),
                ("data_text", models.TextField(blank=True, null=True)),
                (
                    "resources",
                    models.JSONField(
                        default=dict,
                        help_text="{resource_name: pre-change text} for changing resources only.",
                    ),
                ),
                (
                    "item_modified_at",
                    models.BigIntegerField(
                        help_text="item.modified epoch ms at backup time.", null=True
                    ),
                ),
                (
                    "applied_modified_at",
                    models.BigIntegerField(
                        help_text="item.modified epoch ms right after this job updated the item; lets revert detect (and flag) edits made after the replacement.",
                        null=True,
                    ),
                ),
                (
                    "counts",
                    models.JSONField(
                        default=dict,
                        help_text="{'url': n, 'data': n, 'resources': n} replacements applied.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("analyzed", "Analyzed"),
                            ("applied", "Applied"),
                            ("failed", "Failed"),
                            ("apply_failed", "Partially Applied (Failed)"),
                            ("skipped", "Skipped"),
                            ("reverted", "Reverted"),
                            ("revert_failed", "Revert Failed"),
                        ],
                        default="analyzed",
                        max_length=20,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "revert_claimed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when a revert claims this backup, so a concurrent duplicate request or redelivered task cannot revert it twice. Cleared when the revert finishes; a claim older than REVERT_CLAIM_LEASE is treated as abandoned and becomes claimable again.",
                        null=True,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_backups",
                        to="app.replacementjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Replacement Item Backup",
                "verbose_name_plural": "Replacement Item Backups",
            },
        ),
        migrations.AddIndex(
            model_name="replacementjob",
            index=models.Index(
                fields=["portal_instance", "status"],
                name="app_replace_portal__51c2e8_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="replacementitembackup",
            unique_together={("job", "item_id")},
        ),
    ]
