# Generated by Django 5.2.8 on 2026-07-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0018_replacementjob_replacementitembackup_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="layer",
            name="layer_used_by_apps",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="layer",
            name="layer_used_by_count",
            field=models.IntegerField(
                db_index=True, default=0, editable=False, verbose_name="Used By"
            ),
        ),
        migrations.AddField(
            model_name="layer",
            name="layer_used_by_maps",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="layer",
            name="layer_used_by_services",
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
