# Generated by Django 5.2.8 on 2026-07-24 16:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0021_portal_auth_method_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="layer",
            name="layer_used_by_apps",
        ),
        migrations.RemoveField(
            model_name="layer",
            name="layer_used_by_count",
        ),
        migrations.RemoveField(
            model_name="layer",
            name="layer_used_by_maps",
        ),
        migrations.RemoveField(
            model_name="layer",
            name="layer_used_by_services",
        ),
    ]
