# Generated by Django 5.2.8 on 2026-08-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0023_encrypt_sitesettings_email_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="layer",
            name="layer_used_by_apps",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="layer",
            name="layer_used_by_count",
            field=models.IntegerField(
                db_index=True, default=0, editable=False, verbose_name="Used By"
            ),
        ),
        migrations.AddField(
            model_name="layer",
            name="layer_used_by_maps",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="layer",
            name="layer_used_by_services",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="email_password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
