# Generated by Django 5.2.8 on 2026-08-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0027_alter_sitesettings_email_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
